Unregister JMX bean.
scalecube/scalecube-cluster pull request #363
Opened 2021-05-24 12:53 UTC by SammyVimes

Also: 
Clean up resources in ClusterTest

2021-05-26 09:26 UTC, artem-v requested changes
Plz fix minor CR comment. Overall looks good. Thnks.

2021-05-26 09:26 UTC, artem-v commented on cluster/src/test/java/io/scalecube/cluster/ClusterTest.java
> +import java.util.*;
Revert back imports. Adjust your import settings.

2021-05-31 12:28 UTC, SammyVimes commented on cluster/src/test/java/io/scalecube/cluster/ClusterTest.java
> +import java.util.*;
Thanks, fixed

2021-06-01 09:27 UTC, merged

2021-06-01 09:29 UTC, ronenhamias commented
@SammyVimes thank you!